Name:           perl-Net-MQTT-Simple-One_Shot_Loader
Version:        0.01
Release:        1%{?dist}
Summary:        Perl extension to add one_shot method to Net::MQTT::Simple and Net::MQTT::Simple::SSL
License:        MIT
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Net-MQTT-Simple-One_Shot_Loader/
Source0:        http://www.cpan.org/modules/by-module/Net/Net-MQTT-Simple-One_Shot_Loader-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Net::MQTT::Simple) >= 1.24
Requires:       perl(Net::MQTT::Simple) >= 1.24
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
METHODS

%prep
%setup -q -n Net-MQTT-Simple-One_Shot_Loader-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc LICENSE
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Mar 16 2023 Michael R. Davis <mrdvt92@yahoo.com> 0.01-1
- Specfile autogenerated by cpanspec 1.78.
